"""Runtime configuration for MCP/ngrok local setup."""

NGROK_DOMAIN = "fossil-unicorn-defuse.ngrok-free.dev"
NGROK_TUNNEL_ID = "rd_..."
FASTAPI_PORT = 9147
FAST_MCP_PORT = 8000
DASHBOARD_PORT = 7999
PENTEST_MCP_PORT = 8001
PENTEST_MAX_SESSIONS = 10
PENTEST_DEFAULT_TIMEOUT = 30
PENTEST_WSL_DISTRO = "Ubuntu"
ROUTER_MCP_PORT = 8002
ROUTER_HOST = "192.168.1.1"
ROUTER_USERNAME = "root"
